In [1]:
import pandas as pd
import sqlite3
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pd.set_option('display.float_format', '{:.2f}'.format)
pd.set_option('display.float_format', '{:,.2f}'.format)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_pickle(r'D:\Projects\Cafe db\filtered_data')

In [4]:
df.head()

,rnm,num_check,datetime,time_eat,smena,good,total_chek,price,pr_bez_nds,avg_price,profit,amount,position_good,summa,payment,check_unique,group,on-group,seasons,day,hour,date,revenue,mnth,quart
0,6916860058096,92970,2024-01-09 08:06:00,Ранний завтрак,240,Яичница с беконом,181.00,45.00,37.50,22.95,14.55,1.00,1,181.00,card,92970 - 6916860058096,Завтрак,Яичница,Зима,Вторник,8,2024-01-09,37.50,Январь,1 Квартал
1,6916860058096,92970,2024-01-09 08:06:00,Ранний завтрак,240,Сосиски отварные,181.00,65.00,54.17,23.78,30.39,1.00,2,181.00,card,92970 - 6916860058096,Основное блюдо,Колбаски разные,Зима,Вторник,8,2024-01-09,54.17,Январь,1 Квартал
2,6916860058096,92970,2024-01-09 08:06:00,Ранний завтрак,240,Каша овсяная на молоке,181.00,65.00,54.17,13.75,40.42,1.00,3,181.00,card,92970 - 6916860058096,Завтрак,Каши,Зима,Вторник,8,2024-01-09,54.17,Январь,1 Квартал
3,6916860058096,92970,2024-01-09 08:06:00,Ранний завтрак,240,Хлеб ржано-пшеничный,181.00,6.00,5.00,1.84,3.16,1.00,4,181.00,card,92970 - 6916860058096,Хлеб,Хлеб,Зима,Вторник,8,2024-01-09,5.00,Январь,1 Квартал
4,6916860058096,92971,2024-01-09 08:07:00,Ранний завтрак,240,Каша рисовая на молоке,145.00,65.00,54.17,17.42,36.75,1.00,1,145.00,card,92971 - 6916860058096,Завтрак,Каши,Зима,Вторник,8,2024-01-09,54.17,Январь,1 Квартал

In [5]:
df_breakfast = df[df['group'] == 'Завтрак']

In [6]:
df_breakfast

,rnm,num_check,datetime,time_eat,smena,good,total_chek,price,pr_bez_nds,avg_price,profit,amount,position_good,summa,payment,check_unique,group,on-group,seasons,day,hour,date,revenue,mnth,quart
0,6916860058096,92970,2024-01-09 08:06:00,Ранний завтрак,240,Яичница с беконом,181.00,45.00,37.50,22.95,14.55,1.00,1,181.00,card,92970 - 6916860058096,Завтрак,Яичница,Зима,Вторник,8,2024-01-09,37.50,Январь,1 Квартал
2,6916860058096,92970,2024-01-09 08:06:00,Ранний завтрак,240,Каша овсяная на молоке,181.00,65.00,54.17,13.75,40.42,1.00,3,181.00,card,92970 - 6916860058096,Завтрак,Каши,Зима,Вторник,8,2024-01-09,54.17,Январь,1 Квартал
4,6916860058096,92971,2024-01-09 08:07:00,Ранний завтрак,240,Каша рисовая на молоке,145.00,65.00,54.17,17.42,36.75,1.00,1,145.00,card,92971 - 6916860058096,Завтрак,Каши,Зима,Вторник,8,2024-01-09,54.17,Январь,1 Квартал
7,6916860058096,92972,2024-01-09 08:07:00,Ранний завтрак,240,Каша рисовая на молоке,75.00,65.00,54.17,17.42,36.75,1.00,2,75.00,card,92972 - 6916860058096,Завтрак,Каши,Зима,Вторник,8,2024-01-09,54.17,Январь,1 Квартал
9,6916860058096,92973,2024-01-09 08:10:00,Ранний завтрак,240,Яичница с беконом,95.00,45.00,37.50,22.95,14.55,1.00,2,95.00,card,92973 - 6916860058096,Завтрак,Яичница,Зима,Вторник,8,2024-01-09,37.50,Январь,1 Квартал
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482477,6916962051742,19137,2024-10-31 15:03:00,Послеобеденный,194,Каша перловая с овощами,405.00,50.00,41.67,8.57,33.10,1.00,2,405.00,card,19137 - 6916962051742,Завтрак,Каши,Осень,Четверг,15,2024-10-31,41.67,Октябрь,4 Квартал
482646,6916962051742,19167,2024-10-31 15:33:00,Послеобеденный,194,Каша перловая с овощами,235.00,50.00,41.67,8.57,33.10,1.00,1,235.00,card,19167 - 6916962051742,Завтрак,Каши,Осень,Четверг,15,2024-10-31,41.67,Октябрь,4 Квартал
482703,6916962051742,19173,2024-10-31 15:51:00,Послеобеденный,194,Каша перловая с овощами,465.00,50.00,41.67,8.57,33.10,1.00,4,465.00,card,19173 - 6916962051742,Завтрак,Каши,Осень,Четверг,15,2024-10-31,41.67,Октябрь,4 Квартал
482732,6916860058096,104976,2024-10-31 16:00:00,Скидки,195,Йогурт с мюсли,76.00,76.00,63.33,41.79,21.54,1.00,1,76.00,card,104976 - 6916860058096,Завтрак,Мюсли,Осень,Четверг,16,2024-10-31,63.33,Октябрь,4 Квартал
482866,6916860058096,104999,2024-10-31 16:17:00,Скидки,195,Творог порционный,127.00,52.00,43.33,23.63,19.70,1.00,1,127.00,card,104999 - 6916860058096,Завтрак,Из творога,Осень,Четверг,16,2024-10-31,43.33,Октябрь,4 Квартал